version: "3.9"

services:
  db:
    image: postgres:16-alpine
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./themes/puskeu/.:/opt/keycloak/themes/puskeu
    # env_file:
    #   - ./.env
    ports:
      - "8080:8080"
      # - "8443:8443"
    depends_on:
      - db
    networks:
      - keycloak_network

volumes:
  pg_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
